/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddDoctorInput {
  'fees' : bigint,
  'name' : string,
  'availability' : Array<DaySchedule>,
  'specialization' : string,
}
export type AppointmentId = bigint;
export interface AppointmentPublic {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'patientId' : UserId,
  'date' : string,
  'fees' : bigint,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'timeSlot' : string,
}
export type AppointmentStatus = { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Upcoming' : null };
export interface BookAppointmentInput {
  'doctorId' : DoctorId,
  'date' : string,
  'timeSlot' : string,
}
export type DayOfWeek = { 'Saturday' : null } |
  { 'Thursday' : null } |
  { 'Sunday' : null } |
  { 'Tuesday' : null } |
  { 'Friday' : null } |
  { 'Wednesday' : null } |
  { 'Monday' : null };
export interface DaySchedule { 'day' : DayOfWeek, 'slots' : Array<TimeSlot> }
export type DoctorId = bigint;
export interface DoctorPublic {
  'id' : DoctorId,
  'fees' : bigint,
  'name' : string,
  'createdAt' : Timestamp,
  'isActive' : boolean,
  'availability' : Array<DaySchedule>,
  'specialization' : string,
}
export interface PatientProfilePublic {
  'dateOfBirth' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : string,
  'phone' : string,
  'principalId' : UserId,
}
export interface RegisterPatientInput {
  'dateOfBirth' : string,
  'name' : string,
  'email' : string,
  'phone' : string,
}
export interface RescheduleInput {
  'newTimeSlot' : string,
  'appointmentId' : AppointmentId,
  'newDate' : string,
}
export type Role = { 'Admin' : null } |
  { 'Patient' : null };
export type TimeSlot = string;
export type Timestamp = bigint;
export interface UpdateDoctorInput {
  'fees' : [] | [bigint],
  'name' : [] | [string],
  'isActive' : [] | [boolean],
  'availability' : [] | [Array<DaySchedule>],
  'specialization' : [] | [string],
}
export type UserId = Principal;
export interface _SERVICE {
  'addDoctor' : ActorMethod<[AddDoctorInput], DoctorPublic>,
  'assignAdmin' : ActorMethod<[UserId], undefined>,
  'bookAppointment' : ActorMethod<
    [BookAppointmentInput],
    { 'ok' : AppointmentPublic } |
      { 'doubleBooking' : null }
  >,
  'cancelAppointment' : ActorMethod<
    [AppointmentId],
    { 'ok' : null } |
      { 'notFound' : null } |
      { 'unauthorized' : null }
  >,
  'deleteDoctor' : ActorMethod<[DoctorId], boolean>,
  'getAllAppointments' : ActorMethod<[], Array<AppointmentPublic>>,
  'getAvailableSlots' : ActorMethod<
    [DoctorId, string, DayOfWeek],
    Array<TimeSlot>
  >,
  'getDoctor' : ActorMethod<[DoctorId], [] | [DoctorPublic]>,
  'getMyAppointments' : ActorMethod<[], Array<AppointmentPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [PatientProfilePublic]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listDoctors' : ActorMethod<[], Array<DoctorPublic>>,
  'registerPatient' : ActorMethod<[RegisterPatientInput], PatientProfilePublic>,
  'rescheduleAppointment' : ActorMethod<
    [RescheduleInput],
    { 'ok' : AppointmentPublic } |
      { 'notFound' : null } |
      { 'unauthorized' : null } |
      { 'alreadyBooked' : null }
  >,
  'updateDoctor' : ActorMethod<
    [DoctorId, UpdateDoctorInput],
    [] | [DoctorPublic]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];