/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayOfWeek = IDL.Variant({
  'Saturday' : IDL.Null,
  'Thursday' : IDL.Null,
  'Sunday' : IDL.Null,
  'Tuesday' : IDL.Null,
  'Friday' : IDL.Null,
  'Wednesday' : IDL.Null,
  'Monday' : IDL.Null,
});
export const TimeSlot = IDL.Text;
export const DaySchedule = IDL.Record({
  'day' : DayOfWeek,
  'slots' : IDL.Vec(TimeSlot),
});
export const AddDoctorInput = IDL.Record({
  'fees' : IDL.Nat,
  'name' : IDL.Text,
  'availability' : IDL.Vec(DaySchedule),
  'specialization' : IDL.Text,
});
export const DoctorId = IDL.Nat;
export const Timestamp = IDL.Int;
export const DoctorPublic = IDL.Record({
  'id' : DoctorId,
  'fees' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'isActive' : IDL.Bool,
  'availability' : IDL.Vec(DaySchedule),
  'specialization' : IDL.Text,
});
export const UserId = IDL.Principal;
export const BookAppointmentInput = IDL.Record({
  'doctorId' : DoctorId,
  'date' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Upcoming' : IDL.Null,
});
export const AppointmentPublic = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'doctorId' : DoctorId,
  'patientId' : UserId,
  'date' : IDL.Text,
  'fees' : IDL.Nat,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'timeSlot' : IDL.Text,
});
export const Role = IDL.Variant({ 'Admin' : IDL.Null, 'Patient' : IDL.Null });
export const PatientProfilePublic = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'principalId' : UserId,
});
export const RegisterPatientInput = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const RescheduleInput = IDL.Record({
  'newTimeSlot' : IDL.Text,
  'appointmentId' : AppointmentId,
  'newDate' : IDL.Text,
});
export const UpdateDoctorInput = IDL.Record({
  'fees' : IDL.Opt(IDL.Nat),
  'name' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Opt(IDL.Bool),
  'availability' : IDL.Opt(IDL.Vec(DaySchedule)),
  'specialization' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'addDoctor' : IDL.Func([AddDoctorInput], [DoctorPublic], []),
  'assignAdmin' : IDL.Func([UserId], [], []),
  'bookAppointment' : IDL.Func(
      [BookAppointmentInput],
      [IDL.Variant({ 'ok' : AppointmentPublic, 'doubleBooking' : IDL.Null })],
      [],
    ),
  'cancelAppointment' : IDL.Func(
      [AppointmentId],
      [
        IDL.Variant({
          'ok' : IDL.Null,
          'notFound' : IDL.Null,
          'unauthorized' : IDL.Null,
        }),
      ],
      [],
    ),
  'deleteDoctor' : IDL.Func([DoctorId], [IDL.Bool], []),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentPublic)], []),
  'getAvailableSlots' : IDL.Func(
      [DoctorId, IDL.Text, DayOfWeek],
      [IDL.Vec(TimeSlot)],
      ['query'],
    ),
  'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(DoctorPublic)], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(AppointmentPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfilePublic)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listDoctors' : IDL.Func([], [IDL.Vec(DoctorPublic)], ['query']),
  'registerPatient' : IDL.Func(
      [RegisterPatientInput],
      [PatientProfilePublic],
      [],
    ),
  'rescheduleAppointment' : IDL.Func(
      [RescheduleInput],
      [
        IDL.Variant({
          'ok' : AppointmentPublic,
          'notFound' : IDL.Null,
          'unauthorized' : IDL.Null,
          'alreadyBooked' : IDL.Null,
        }),
      ],
      [],
    ),
  'updateDoctor' : IDL.Func(
      [DoctorId, UpdateDoctorInput],
      [IDL.Opt(DoctorPublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayOfWeek = IDL.Variant({
    'Saturday' : IDL.Null,
    'Thursday' : IDL.Null,
    'Sunday' : IDL.Null,
    'Tuesday' : IDL.Null,
    'Friday' : IDL.Null,
    'Wednesday' : IDL.Null,
    'Monday' : IDL.Null,
  });
  const TimeSlot = IDL.Text;
  const DaySchedule = IDL.Record({
    'day' : DayOfWeek,
    'slots' : IDL.Vec(TimeSlot),
  });
  const AddDoctorInput = IDL.Record({
    'fees' : IDL.Nat,
    'name' : IDL.Text,
    'availability' : IDL.Vec(DaySchedule),
    'specialization' : IDL.Text,
  });
  const DoctorId = IDL.Nat;
  const Timestamp = IDL.Int;
  const DoctorPublic = IDL.Record({
    'id' : DoctorId,
    'fees' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'isActive' : IDL.Bool,
    'availability' : IDL.Vec(DaySchedule),
    'specialization' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const BookAppointmentInput = IDL.Record({
    'doctorId' : DoctorId,
    'date' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Upcoming' : IDL.Null,
  });
  const AppointmentPublic = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'doctorId' : DoctorId,
    'patientId' : UserId,
    'date' : IDL.Text,
    'fees' : IDL.Nat,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'timeSlot' : IDL.Text,
  });
  const Role = IDL.Variant({ 'Admin' : IDL.Null, 'Patient' : IDL.Null });
  const PatientProfilePublic = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'principalId' : UserId,
  });
  const RegisterPatientInput = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const RescheduleInput = IDL.Record({
    'newTimeSlot' : IDL.Text,
    'appointmentId' : AppointmentId,
    'newDate' : IDL.Text,
  });
  const UpdateDoctorInput = IDL.Record({
    'fees' : IDL.Opt(IDL.Nat),
    'name' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Opt(IDL.Bool),
    'availability' : IDL.Opt(IDL.Vec(DaySchedule)),
    'specialization' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'addDoctor' : IDL.Func([AddDoctorInput], [DoctorPublic], []),
    'assignAdmin' : IDL.Func([UserId], [], []),
    'bookAppointment' : IDL.Func(
        [BookAppointmentInput],
        [IDL.Variant({ 'ok' : AppointmentPublic, 'doubleBooking' : IDL.Null })],
        [],
      ),
    'cancelAppointment' : IDL.Func(
        [AppointmentId],
        [
          IDL.Variant({
            'ok' : IDL.Null,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
          }),
        ],
        [],
      ),
    'deleteDoctor' : IDL.Func([DoctorId], [IDL.Bool], []),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(AppointmentPublic)], []),
    'getAvailableSlots' : IDL.Func(
        [DoctorId, IDL.Text, DayOfWeek],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getDoctor' : IDL.Func([DoctorId], [IDL.Opt(DoctorPublic)], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(AppointmentPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PatientProfilePublic)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listDoctors' : IDL.Func([], [IDL.Vec(DoctorPublic)], ['query']),
    'registerPatient' : IDL.Func(
        [RegisterPatientInput],
        [PatientProfilePublic],
        [],
      ),
    'rescheduleAppointment' : IDL.Func(
        [RescheduleInput],
        [
          IDL.Variant({
            'ok' : AppointmentPublic,
            'notFound' : IDL.Null,
            'unauthorized' : IDL.Null,
            'alreadyBooked' : IDL.Null,
          }),
        ],
        [],
      ),
    'updateDoctor' : IDL.Func(
        [DoctorId, UpdateDoctorInput],
        [IDL.Opt(DoctorPublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };