/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PatientProfilePublic {
    dateOfBirth: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    phone: string;
    principalId: UserId;
}
export type Timestamp = bigint;
export type TimeSlot = string;
export type DoctorId = bigint;
export interface AppointmentPublic {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    patientId: UserId;
    date: string;
    fees: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    timeSlot: string;
}
export interface DaySchedule {
    day: DayOfWeek;
    slots: Array<TimeSlot>;
}
export type AppointmentId = bigint;
export interface AddDoctorInput {
    fees: bigint;
    name: string;
    availability: Array<DaySchedule>;
    specialization: string;
}
export interface DoctorPublic {
    id: DoctorId;
    fees: bigint;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    availability: Array<DaySchedule>;
    specialization: string;
}
export interface BookAppointmentInput {
    doctorId: DoctorId;
    date: string;
    timeSlot: string;
}
export type UserId = Principal;
export interface RegisterPatientInput {
    dateOfBirth: string;
    name: string;
    email: string;
    phone: string;
}
export interface UpdateDoctorInput {
    fees?: bigint;
    name?: string;
    isActive?: boolean;
    availability?: Array<DaySchedule>;
    specialization?: string;
}
export interface RescheduleInput {
    newTimeSlot: string;
    appointmentId: AppointmentId;
    newDate: string;
}
export enum AppointmentStatus {
    Cancelled = "Cancelled",
    Completed = "Completed",
    Upcoming = "Upcoming"
}
export enum DayOfWeek {
    Saturday = "Saturday",
    Thursday = "Thursday",
    Sunday = "Sunday",
    Tuesday = "Tuesday",
    Friday = "Friday",
    Wednesday = "Wednesday",
    Monday = "Monday"
}
export enum Role {
    Admin = "Admin",
    Patient = "Patient"
}
export enum Variant_ok_notFound_unauthorized {
    ok = "ok",
    notFound = "notFound",
    unauthorized = "unauthorized"
}
export interface backendInterface {
    addDoctor(input: AddDoctorInput): Promise<DoctorPublic>;
    assignAdmin(targetPrincipal: UserId): Promise<void>;
    bookAppointment(input: BookAppointmentInput): Promise<{
        __kind__: "ok";
        ok: AppointmentPublic;
    } | {
        __kind__: "doubleBooking";
        doubleBooking: null;
    }>;
    cancelAppointment(appointmentId: AppointmentId): Promise<Variant_ok_notFound_unauthorized>;
    deleteDoctor(id: DoctorId): Promise<boolean>;
    getAllAppointments(): Promise<Array<AppointmentPublic>>;
    getAvailableSlots(doctorId: DoctorId, date: string, dayOfWeek: DayOfWeek): Promise<Array<TimeSlot>>;
    getDoctor(id: DoctorId): Promise<DoctorPublic | null>;
    getMyAppointments(): Promise<Array<AppointmentPublic>>;
    getMyProfile(): Promise<PatientProfilePublic | null>;
    isAdmin(): Promise<boolean>;
    listDoctors(): Promise<Array<DoctorPublic>>;
    registerPatient(input: RegisterPatientInput): Promise<PatientProfilePublic>;
    rescheduleAppointment(input: RescheduleInput): Promise<{
        __kind__: "ok";
        ok: AppointmentPublic;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "unauthorized";
        unauthorized: null;
    } | {
        __kind__: "alreadyBooked";
        alreadyBooked: null;
    }>;
    updateDoctor(id: DoctorId, input: UpdateDoctorInput): Promise<DoctorPublic | null>;
}
import type { AddDoctorInput as _AddDoctorInput, AppointmentId as _AppointmentId, AppointmentPublic as _AppointmentPublic, AppointmentStatus as _AppointmentStatus, DayOfWeek as _DayOfWeek, DaySchedule as _DaySchedule, DoctorId as _DoctorId, DoctorPublic as _DoctorPublic, PatientProfilePublic as _PatientProfilePublic, Role as _Role, TimeSlot as _TimeSlot, Timestamp as _Timestamp, UpdateDoctorInput as _UpdateDoctorInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDoctor(arg0: AddDoctorInput): Promise<DoctorPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addDoctor(to_candid_AddDoctorInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DoctorPublic_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDoctor(to_candid_AddDoctorInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DoctorPublic_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignAdmin(arg0);
            return result;
        }
    }
    async bookAppointment(arg0: BookAppointmentInput): Promise<{
        __kind__: "ok";
        ok: AppointmentPublic;
    } | {
        __kind__: "doubleBooking";
        doubleBooking: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: AppointmentId): Promise<Variant_ok_notFound_unauthorized> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteDoctor(arg0: DoctorId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDoctor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDoctor(arg0);
            return result;
        }
    }
    async getAllAppointments(): Promise<Array<AppointmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAppointments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAppointments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableSlots(arg0: DoctorId, arg1: string, arg2: DayOfWeek): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableSlots(arg0, arg1, to_candid_DayOfWeek_n6(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableSlots(arg0, arg1, to_candid_DayOfWeek_n6(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getDoctor(arg0: DoctorId): Promise<DoctorPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctor(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctor(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAppointments(): Promise<Array<AppointmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAppointments();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAppointments();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<PatientProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listDoctors(): Promise<Array<DoctorPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listDoctors();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listDoctors();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerPatient(arg0: RegisterPatientInput): Promise<PatientProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.registerPatient(arg0);
                return from_candid_PatientProfilePublic_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerPatient(arg0);
            return from_candid_PatientProfilePublic_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async rescheduleAppointment(arg0: RescheduleInput): Promise<{
        __kind__: "ok";
        ok: AppointmentPublic;
    } | {
        __kind__: "notFound";
        notFound: null;
    } | {
        __kind__: "unauthorized";
        unauthorized: null;
    } | {
        __kind__: "alreadyBooked";
        alreadyBooked: null;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleAppointment(arg0);
                return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleAppointment(arg0);
            return from_candid_variant_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateDoctor(arg0: DoctorId, arg1: UpdateDoctorInput): Promise<DoctorPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDoctor(arg0, to_candid_UpdateDoctorInput_n30(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDoctor(arg0, to_candid_UpdateDoctorInput_n30(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AppointmentPublic_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentPublic): AppointmentPublic {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentStatus_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_DayOfWeek_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DaySchedule_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DaySchedule): DaySchedule {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_DoctorPublic_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoctorPublic): DoctorPublic {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PatientProfilePublic_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PatientProfilePublic): PatientProfilePublic {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DoctorPublic]): DoctorPublic | null {
    return value.length === 0 ? null : from_candid_DoctorPublic_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfilePublic]): PatientProfilePublic | null {
    return value.length === 0 ? null : from_candid_PatientProfilePublic_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    slots: Array<_TimeSlot>;
}): {
    day: DayOfWeek;
    slots: Array<TimeSlot>;
} {
    return {
        day: from_candid_DayOfWeek_n13(_uploadFile, _downloadFile, value.day),
        slots: value.slots
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    status: _AppointmentStatus;
    doctorId: _DoctorId;
    patientId: _UserId;
    date: string;
    fees: bigint;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    timeSlot: string;
}): {
    id: AppointmentId;
    status: AppointmentStatus;
    doctorId: DoctorId;
    patientId: UserId;
    date: string;
    fees: bigint;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n18(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        date: value.date,
        fees: value.fees,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dateOfBirth: string;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    email: string;
    phone: string;
    principalId: _UserId;
}): {
    dateOfBirth: string;
    name: string;
    createdAt: Timestamp;
    role: Role;
    email: string;
    phone: string;
    principalId: UserId;
} {
    return {
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n26(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone,
        principalId: value.principalId
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DoctorId;
    fees: bigint;
    name: string;
    createdAt: _Timestamp;
    isActive: boolean;
    availability: Array<_DaySchedule>;
    specialization: string;
}): {
    id: DoctorId;
    fees: bigint;
    name: string;
    createdAt: Timestamp;
    isActive: boolean;
    availability: Array<DaySchedule>;
    specialization: string;
} {
    return {
        id: value.id,
        fees: value.fees,
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        availability: from_candid_vec_n10(_uploadFile, _downloadFile, value.availability),
        specialization: value.specialization
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Saturday: null;
} | {
    Thursday: null;
} | {
    Sunday: null;
} | {
    Tuesday: null;
} | {
    Friday: null;
} | {
    Wednesday: null;
} | {
    Monday: null;
}): DayOfWeek {
    return "Saturday" in value ? DayOfWeek.Saturday : "Thursday" in value ? DayOfWeek.Thursday : "Sunday" in value ? DayOfWeek.Sunday : "Tuesday" in value ? DayOfWeek.Tuesday : "Friday" in value ? DayOfWeek.Friday : "Wednesday" in value ? DayOfWeek.Wednesday : "Monday" in value ? DayOfWeek.Monday : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AppointmentPublic;
} | {
    doubleBooking: null;
}): {
    __kind__: "ok";
    ok: AppointmentPublic;
} | {
    __kind__: "doubleBooking";
    doubleBooking: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AppointmentPublic_n16(_uploadFile, _downloadFile, value.ok)
    } : "doubleBooking" in value ? {
        __kind__: "doubleBooking",
        doubleBooking: value.doubleBooking
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Upcoming: null;
}): AppointmentStatus {
    return "Cancelled" in value ? AppointmentStatus.Cancelled : "Completed" in value ? AppointmentStatus.Completed : "Upcoming" in value ? AppointmentStatus.Upcoming : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    notFound: null;
} | {
    unauthorized: null;
}): Variant_ok_notFound_unauthorized {
    return "ok" in value ? Variant_ok_notFound_unauthorized.ok : "notFound" in value ? Variant_ok_notFound_unauthorized.notFound : "unauthorized" in value ? Variant_ok_notFound_unauthorized.unauthorized : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Admin: null;
} | {
    Patient: null;
}): Role {
    return "Admin" in value ? Role.Admin : "Patient" in value ? Role.Patient : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AppointmentPublic;
} | {
    notFound: null;
} | {
    unauthorized: null;
} | {
    alreadyBooked: null;
}): {
    __kind__: "ok";
    ok: AppointmentPublic;
} | {
    __kind__: "notFound";
    notFound: null;
} | {
    __kind__: "unauthorized";
    unauthorized: null;
} | {
    __kind__: "alreadyBooked";
    alreadyBooked: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_AppointmentPublic_n16(_uploadFile, _downloadFile, value.ok)
    } : "notFound" in value ? {
        __kind__: "notFound",
        notFound: value.notFound
    } : "unauthorized" in value ? {
        __kind__: "unauthorized",
        unauthorized: value.unauthorized
    } : "alreadyBooked" in value ? {
        __kind__: "alreadyBooked",
        alreadyBooked: value.alreadyBooked
    } : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DaySchedule>): Array<DaySchedule> {
    return value.map((x)=>from_candid_DaySchedule_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AppointmentPublic>): Array<AppointmentPublic> {
    return value.map((x)=>from_candid_AppointmentPublic_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoctorPublic>): Array<DoctorPublic> {
    return value.map((x)=>from_candid_DoctorPublic_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AddDoctorInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddDoctorInput): _AddDoctorInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_DayOfWeek_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_DaySchedule_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DaySchedule): _DaySchedule {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateDoctorInput_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateDoctorInput): _UpdateDoctorInput {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fees: bigint;
    name: string;
    availability: Array<DaySchedule>;
    specialization: string;
}): {
    fees: bigint;
    name: string;
    availability: Array<_DaySchedule>;
    specialization: string;
} {
    return {
        fees: value.fees,
        name: value.name,
        availability: to_candid_vec_n3(_uploadFile, _downloadFile, value.availability),
        specialization: value.specialization
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fees?: bigint;
    name?: string;
    isActive?: boolean;
    availability?: Array<DaySchedule>;
    specialization?: string;
}): {
    fees: [] | [bigint];
    name: [] | [string];
    isActive: [] | [boolean];
    availability: [] | [Array<_DaySchedule>];
    specialization: [] | [string];
} {
    return {
        fees: value.fees ? candid_some(value.fees) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        isActive: value.isActive ? candid_some(value.isActive) : candid_none(),
        availability: value.availability ? candid_some(to_candid_vec_n3(_uploadFile, _downloadFile, value.availability)) : candid_none(),
        specialization: value.specialization ? candid_some(value.specialization) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: DayOfWeek;
    slots: Array<TimeSlot>;
}): {
    day: _DayOfWeek;
    slots: Array<_TimeSlot>;
} {
    return {
        day: to_candid_DayOfWeek_n6(_uploadFile, _downloadFile, value.day),
        slots: value.slots
    };
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    Saturday: null;
} | {
    Thursday: null;
} | {
    Sunday: null;
} | {
    Tuesday: null;
} | {
    Friday: null;
} | {
    Wednesday: null;
} | {
    Monday: null;
} {
    return value == DayOfWeek.Saturday ? {
        Saturday: null
    } : value == DayOfWeek.Thursday ? {
        Thursday: null
    } : value == DayOfWeek.Sunday ? {
        Sunday: null
    } : value == DayOfWeek.Tuesday ? {
        Tuesday: null
    } : value == DayOfWeek.Friday ? {
        Friday: null
    } : value == DayOfWeek.Wednesday ? {
        Wednesday: null
    } : value == DayOfWeek.Monday ? {
        Monday: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DaySchedule>): Array<_DaySchedule> {
    return value.map((x)=>to_candid_DaySchedule_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
